name: base
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - aiofiles
  - aiosqlite
  - anyio
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - boltons
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - conda
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - filelock
  - flit-core
  - fmt
  - freetype
  - gmp
  - gmpy2
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - json5
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_fileid
  - jupyter_server_terminals
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - krb5
  - lcms2
  - lerc
  - libarchive
  - libblas
  - libcblas
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libiconv
  - libjpeg-turbo
  - liblapack
  - libmamba
  - libmambapy
  - libnghttp2
  - libopenblas
  - libpng
  - libprotobuf
  - libsodium
  - libsolv
  - libsqlite
  - libssh2
  - libtiff
  - libwebp-base
  - libxcb
  - libxml2
  - libzlib
  - llvm-openmp
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - matplotlib-inline
  - mistune
  - mpc
  - mpfr
  - mpmath
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - networkx
  - notebook
  - notebook-shim
  - numpy
  - openjpeg
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - parso
  - pexpect
  - pickleshare
  - pillow
  - pip
  - pkgutil-resolve-name
  - platformdirs
  - pluggy
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - pybind11-abi
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python_abi
  - pytorch
  - pytz
  - pyyaml
  - pyzmq
  - readline
  - reproc
  - reproc-cpp
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - ruamel.yaml
  - ruamel.yaml.clib
  - send2trash
  - setuptools
  - six
  - sleef
  - sniffio
  - soupsieve
  - stack_data
  - sympy
  - terminado
  - tinycss2
  - tk
  - tomli
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - y-py
  - yaml
  - yaml-cpp
  - ypy-websocket
  - zeromq
  - zipp
  - zstandard
  - zstd
