name: base
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - conda-forge
  - defaults
dependencies:
  - anyio
  - aom
  - appdirs
  - appnope
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - babel
  - backcall
  - beautifulsoup4
  - blas
  - bleach
  - boltons
  - bottleneck
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - certifi
  - cffi
  - charset-normalizer
  - colorama
  - comm
  - conda
  - conda-package-handling
  - conda-package-streaming
  - cryptography
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - ffmpeg
  - filelock
  - flit-core
  - fmt
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-anaconda
  - fonts-conda-ecosystem
  - freetype
  - gettext
  - giflib
  - glib
  - glib-tools
  - gmp
  - gmpy2
  - gnutls
  - gst-plugins-base
  - gstreamer
  - icu
  - idna
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jpeg
  - json5
  - jsonpatch
  - jsonpointer
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - krb5
  - lame
  - lcms2
  - lerc
  - libarchive
  - libclang
  - libclang13
  - libcurl
  - libcxx
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgfortran
  - libgfortran5
  - libglib
  - libiconv
  - libidn2
  - libllvm14
  - libmamba
  - libmambapy
  - libnghttp2
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libsodium
  - libsolv
  - libsqlite
  - libssh2
  - libtasn1
  - libtiff
  - libunistring
  - libvorbis
  - libvpx
  - libwebp
  - libwebp-base
  - libxml2
  - libxslt
  - libzlib
  - llvm-openmp
  - lxml
  - lz4-c
  - lzo
  - mamba
  - markupsafe
  - matplotlib-inline
  - mistune
  - mpc
  - mpfr
  - mysql-common
  - mysql-libs
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numexpr
  - numpy
  - numpy-base
  - openh264
  - openssl
  - p11-kit
  - packaging
  - pandas
  - pandocfilters
  - parso
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pip
  - platformdirs
  - pluggy
  - ply
  - pooch
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pybind11-abi
  - pycosat
  - pycparser
  - pygments
  - pyopenssl
  - pyqt
  - pyrsistent
  - pysocks
  - python
  - python-dateutil
  - python-fastjsonschema
  - python_abi
  - pytorch
  - pytz
  - pyzmq
  - qt-main
  - qt-webengine
  - qtconsole
  - qtpy
  - qtwebkit
  - readline
  - reproc
  - reproc-cpp
  - requests
  - ruamel.yaml
  - ruamel.yaml.clib
  - scipy
  - send2trash
  - setuptools
  - sip
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - statsmodels
  - svt-av1
  - sympy
  - terminado
  - tinycss2
  - tk
  - toml
  - tomli
  - toolz
  - torchaudio
  - torchvision
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - x264
  - x265
  - xz
  - yaml-cpp
  - zeromq
  - zlib
  - zstandard
  - zstd
  - pip:
      - mpmath
      - pyqt5-sip
